services:
  reol:
    build:
      context: .
      dockerfile: Dockerfile

    image: reol-image
    container_name: reol
    restart: unless-stopped

    env_file:
      - ./.env

    volumes:
      - ./cookies.txt:/app/cookies.txt:rw
      - ./cache:/app/cache:rw
      - ./src/db/db.sqlite:/app/src/db/db.sqlite:rw

    command: ['node', 'dist/index.js']
